<a href="https://colab.research.google.com/github/dipanwitad-create/NASSCOM_FDP_programme/blob/main/Day4/Day4Exercise_Use_case_Statistics_for_Hospital_Patient_Treatment_Analysi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)

data = {
    "Patient_ID": range(1,101),
    "Recovered": np.random.choice(["Yes","No"],100),
    "Treatment_Type": np.random.choice(["Medication","Therapy","Surgery"],100),
    "Disease_Type": np.random.choice(["Cardiac","Diabetes","Respiratory"],100),
    "Insurance": np.random.choice(["Yes","No"],100),
    "Treatment_Cost": np.random.normal(50000,10000,100)
}

df = pd.DataFrame(data)
df.head()

   Patient_ID Recovered Treatment_Type Disease_Type Insurance  Treatment_Cost
0           1       Yes        Surgery     Diabetes        No    49884.166802
1           2        No        Therapy     Diabetes        No    51905.987051
2           3       Yes        Therapy  Respiratory       Yes    56069.757096
3           4       Yes        Therapy     Diabetes        No    46510.988172
4           5       Yes        Therapy  Respiratory       Yes    56061.293631

In [2]:
# Probability that a patient recovers

recovery_prob = (df["Recovered"] == "Yes").mean()

print("Probability of Recovery:", recovery_prob)

Probability of Recovery: 0.44

In [3]:
# Recovery probability by treatment type

pd.crosstab(
    df["Treatment_Type"],
    df["Recovered"],
    normalize="index"
)

Recovered             No       Yes
Treatment_Type
Medication      0.628571  0.371429
Surgery         0.564103  0.435897
Therapy         0.461538  0.538462

In [4]:
# Event A = Surgery
# Event B = Medication

surgery_patients = df[df["Treatment_Type"] == "Surgery"]
medication_patients = df[df["Treatment_Type"] == "Medication"]

# Since one patient can have only one treatment type,
# intersection is always zero

intersection = len(
    df[
        (df["Treatment_Type"] == "Surgery") &
        (df["Treatment_Type"] == "Medication")
    ]
)

print("Number of patients in A ∩ B:", intersection)

if intersection == 0:
    print("\nInterpretation:")
    print("P(A ∩ B) = 0")
    print("A patient cannot receive Surgery and Medication simultaneously.")
    print("Therefore, the events are mutually exclusive.")

Number of patients in A ∩ B: 0

Interpretation:
P(A ∩ B) = 0
A patient cannot receive Surgery and Medication simultaneously.
Therefore, the events are mutually exclusive.

In [5]:
# H0: Treatment type does not affect recovery
# H1: Treatment type affects recovery

print("H0: Treatment type does not affect recovery")
print("H1: Treatment type affects recovery")

H0: Treatment type does not affect recovery
H1: Treatment type affects recovery

In [8]:
# One-Tail vs Two-Tail Test

print("Scenario:")
print("Hospital management believes Surgery has a higher recovery rate than Medication.\n")

print("One-Tail Test")
print("H0: Surgery recovery rate <= Medication recovery rate")
print("H1: Surgery recovery rate > Medication recovery rate")

print("\nTwo-Tail Test")
print("H0: Surgery recovery rate = Medication recovery rate")
print("H1: Surgery recovery rate != Medication recovery rate")


# Recovery rates by treatment type

recovery_rates = pd.crosstab(
    df["Treatment_Type"],
    df["Recovered"],
    normalize="index"
)

print(recovery_rates)

surgery_rate = recovery_rates.loc["Surgery", "Yes"]
medication_rate = recovery_rates.loc["Medication", "Yes"]

print("\nSurgery Recovery Rate:", round(surgery_rate, 3))
print("Medication Recovery Rate:", round(medication_rate, 3))

if surgery_rate > medication_rate:
    print("\nObservation:")
    print("Surgery shows a higher recovery rate than Medication.")
    print("A One-Tail test would investigate whether this difference is statistically significant.")
else:
    print("\nObservation:")
    print("Surgery does not show a higher recovery rate than Medication.")

    print("One-Tail Test:")
print("Used when we want to test whether Surgery performs better than Medication.")

print("\nTwo-Tail Test:")
print("Used when we want to test whether any difference exists between treatment methods.")

Scenario:
Hospital management believes Surgery has a higher recovery rate than Medication.

One-Tail Test
H0: Surgery recovery rate <= Medication recovery rate
H1: Surgery recovery rate > Medication recovery rate

Two-Tail Test
H0: Surgery recovery rate = Medication recovery rate
H1: Surgery recovery rate != Medication recovery rate
Recovered             No       Yes
Treatment_Type
Medication      0.628571  0.371429
Surgery         0.564103  0.435897
Therapy         0.461538  0.538462

Surgery Recovery Rate: 0.436
Medication Recovery Rate: 0.371

Observation:
Surgery shows a higher recovery rate than Medication.
A One-Tail test would investigate whether this difference is statistically significant.
Used when we want to test whether Surgery performs better than Medication.

Two-Tail Test:
Used when we want to test whether any difference exists between treatment methods.

In [9]:
from scipy.stats import chi2_contingency

# Contingency table
table = pd.crosstab(
    df["Treatment_Type"],
    df["Recovered"]
)

# Chi-Square Test
chi2, p, dof, expected = chi2_contingency(table)

print("Chi-Square Statistic:", chi2)
print("p-value:", p)
print("Degrees of Freedom:", dof)

if p < 0.05:
    print("Reject H0")
    print("Treatment type significantly affects recovery")
else:
    print("Fail to Reject H0")
    print("No significant relationship found")

Chi-Square Statistic: 1.6935445506874078
p-value: 0.42879673850893685
Degrees of Freedom: 2
Fail to Reject H0
No significant relationship found

In [10]:
from scipy.stats import f_oneway

# Treatment cost by treatment type
medication = df[df["Treatment_Type"]=="Medication"]["Treatment_Cost"]

therapy = df[df["Treatment_Type"]=="Therapy"]["Treatment_Cost"]

surgery = df[df["Treatment_Type"]=="Surgery"]["Treatment_Cost"]

# ANOVA Test
f_stat, p_value = f_oneway(
    medication,
    therapy,
    surgery
)

print("F Statistic:", f_stat)
print("p-value:", p_value)

if p_value < 0.05:
    print("Reject H0")
    print("Treatment costs differ significantly")
else:
    print("Fail to Reject H0")
    print("No significant cost difference")

F Statistic: 0.7912594579897823
p-value: 0.4561770576044696
Fail to Reject H0
No significant cost difference

In [11]:
print("\n----- HOSPITAL ANALYSIS REPORT -----")

print("Recovery Probability:",
      round((df["Recovered"]=="Yes").mean(),3))

print("\nTreatment vs Recovery")
print(pd.crosstab(df["Treatment_Type"],
                  df["Recovered"]))

print("\nChi-Square p-value:", p)

print("ANOVA p-value:", p_value)

----- HOSPITAL ANALYSIS REPORT -----
Recovery Probability: 0.44

Treatment vs Recovery
Recovered       No  Yes
Treatment_Type
Medication      22   13
Surgery         22   17
Therapy         12   14

Chi-Square p-value: 0.42879673850893685
ANOVA p-value: 0.4561770576044696